apiVersion: v1
kind: Service
metadata:
  name: frontend-nextjs
spec:
  selector:
    app: frontend-nextjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nextjs
  template:
    metadata:
      labels:
        app: frontend-nextjs
    spec:
      containers:
      - name: frontend-nextjs
        image: projet_devops-frontend-nextjs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000