apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS student_db;
    USE student_db;

    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
    FLUSH PRIVILEGES;

    -- ON CRÉE LA TABLE AVEC DES VALEURS PAR DÉFAUT POUR ÉVITER LES 'NULL'
    CREATE TABLE IF NOT EXISTS students (
        id INT AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL,
        phone VARCHAR(20) DEFAULT '',
        enrollment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- Insertion de test 100% sécurisée
    INSERT IGNORE INTO students (first_name, last_name, email, phone) 
    VALUES ('Imhotep', 'DevOps', 'victoire@efrei.fr', '');